# Generated by Django 3.0 on 2019-12-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=220)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.Product')),
            ],
        ),
    ]
