# Generated by Django 3.0 on 2019-12-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0007_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discont_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sklep.Discount'),
        ),
    ]
