# Generated by Django 3.0 on 2019-12-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0008_order_discont_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discont_code',
            new_name='discount_code',
        ),
    ]
